image: mcr.microsoft.com/dotnet/sdk:8.0
before_script:
  - $PSVersionTable.PSVersion
  - dotnet --version
  - nuget help | select-string Version
stages:
  - build
  - test
  - deploy
build job:
  script:
    - dotnet build -c Release 
  stage: build
  only: 
    - merge_requests 
  artifacts:
    paths:
      - BiblioTdd/artifacts
       

test and cover job:
  script:
    - dotnet test -c Release /p:CollectCoverage=true
  coverage: /|s*Totals*|s*(d+[,.]d+%)/ 
  stage: test
  only:
    - merge_requests

pack and deploy job:
  script:
    - dotnet pack -c Release -o .
    - dotnet new nugetconfig
    - nuget sources add -name feedName -source https://pkgs.dev.azure.com/cicdsamples/TddSample1/_packaging/TddSource/nuget/v3/index.json -username cicdsamples -password $nugetFeedToken -configfile nuget.config -StorePasswordInClearText
    - nuget push -source feedName -skipduplicate -apikey az *.nupkg
  only:
    - main 
  stage: deploy 

pages: 
  stage: deploy
  script:
    - nuget install docfx.console -version 2.51.0
    - $env:path = "$env:path;$($(get-location).Path)"
    - .docfx.console.2.51.0toolsdocfx.exe .docfxdocfx.json
  artifacts:
    paths:
      - public
  only:
    - main